#!/usr/bin/env bash
# roomkit one-click VPS installer
# Tested on Ubuntu 22.04 / 24.04
# Usage: curl -fsSL https://raw.githubusercontent.com/dixydo/roomkit/main/install.sh | bash
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/dixydo/roomkit/main"
INSTALL_DIR="${INSTALL_DIR:-$HOME/roomkit}"

# ---- helpers ----------------------------------------------------------------

info()  { printf '\033[0;32m[roomkit]\033[0m %s\n' "$*"; }
warn()  { printf '\033[0;33m[roomkit]\033[0m %s\n' "$*"; }
error() { printf '\033[0;31m[roomkit]\033[0m %s\n' "$*" >&2; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1 || error "required command not found: $1"; }

# ---- docker -----------------------------------------------------------------

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    info "Docker already installed: $(docker --version)"
    return
  fi
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  if getent group docker >/dev/null 2>&1; then
    usermod -aG docker "$USER" || true
    warn "Added $USER to docker group. Run 'newgrp docker' or re-login for group to take effect."
  fi
}

# ---- firewall ---------------------------------------------------------------

configure_firewall() {
  if ! command -v ufw >/dev/null 2>&1; then
    warn "ufw not found; skipping firewall setup. Open ports 22/tcp, 80/tcp, 443/tcp, 3478/udp, 49152-49200/udp manually."
    return
  fi
  info "Configuring firewall (ufw)..."
  ufw allow 22/tcp   >/dev/null
  ufw allow 80/tcp   >/dev/null
  ufw allow 443/tcp  >/dev/null
  ufw allow 3478/udp >/dev/null
  ufw allow 49152:49200/udp >/dev/null
  ufw --force enable >/dev/null
  info "Firewall configured."
}

# ---- detect public IP -------------------------------------------------------

detect_public_ip() {
  curl -fsSL --max-time 5 https://ifconfig.me 2>/dev/null \
    || curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null \
    || echo ""
}

# ---- main -------------------------------------------------------------------

need_cmd curl

info "roomkit installer"
echo ""

# Prompt for domain
if [ -z "${DOMAIN:-}" ]; then
  printf "Enter your domain (e.g. meet.example.com): "
  read -r DOMAIN
fi
[ -z "$DOMAIN" ] && error "DOMAIN is required."

PUBLIC_URL="https://${DOMAIN}"

# Detect public IP for TURN
PUBLIC_IP="${ROOMKIT_TURN_PUBLIC_IP:-$(detect_public_ip)}"
if [ -z "$PUBLIC_IP" ]; then
  warn "Could not detect public IP. Set ROOMKIT_TURN_PUBLIC_IP in .env to enable TURN."
fi

# Generate secrets
TURN_SECRET="${ROOMKIT_TURN_SECRET:-$(openssl rand -hex 32)}"
TOKEN_SECRET="${ROOMKIT_ROOM_TOKEN_SECRET:-$(openssl rand -hex 32)}"

# Create install directory
info "Installing to $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download config files
info "Downloading config files..."
curl -fsSL "$REPO_RAW/docker-compose.yml" -o docker-compose.yml
curl -fsSL "$REPO_RAW/Caddyfile"          -o Caddyfile

# Write .env
if [ -f .env ]; then
  warn ".env already exists — not overwriting. Review it manually."
else
  info "Writing .env..."
  cat > .env << EOF
# Generated by roomkit installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)

DOMAIN=${DOMAIN}
ROOMKIT_PUBLIC_URL=${PUBLIC_URL}
ROOMKIT_ALLOWED_ORIGINS=${PUBLIC_URL}

# Room token auth — keep this secret
ROOMKIT_ROOM_TOKEN_SECRET=${TOKEN_SECRET}

# Embedded TURN — relays media for ~15% of users behind strict NAT
ROOMKIT_TURN_PUBLIC_IP=${PUBLIC_IP}
ROOMKIT_TURN_SECRET=${TURN_SECRET}
ROOMKIT_TURN_PORT=3478
ROOMKIT_TURN_MIN_PORT=49152
ROOMKIT_TURN_MAX_PORT=49200

# Recording — local mode (files saved to Docker volume, served at /recordings/)
ROOMKIT_REC_ENABLED=true
ROOMKIT_REC_MAX_HOURS=8

# Optional: S3-compatible upload (uncomment and fill in to use instead of local)
# ROOMKIT_S3_ENDPOINT=https://fra1.digitaloceanspaces.com
# ROOMKIT_S3_REGION=fra1
# ROOMKIT_S3_BUCKET=my-roomkit-recordings
# ROOMKIT_S3_ACCESS_KEY=DOxxxxxxxxxxxxxxxxxx
# ROOMKIT_S3_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# ROOMKIT_S3_PUBLIC_BASE=https://my-roomkit-recordings.fra1.cdn.digitaloceanspaces.com
EOF
  info ".env written."
fi

# Install Docker
install_docker

# Configure firewall
configure_firewall

# Start services
info "Starting roomkit..."
docker compose pull
docker compose up -d

echo ""
info "Done! roomkit is starting up."
echo ""
echo "  Site:       ${PUBLIC_URL}"
echo "  Health:     ${PUBLIC_URL}/healthz"
echo "  Features:   ${PUBLIC_URL}/api/features"
echo ""
echo "  Logs:       cd ${INSTALL_DIR} && docker compose logs -f"
echo "  Stop:       cd ${INSTALL_DIR} && docker compose down"
echo "  Update:     cd ${INSTALL_DIR} && docker compose pull && docker compose up -d"
echo ""
echo "  DNS: make sure ${DOMAIN} points to this server's IP (${PUBLIC_IP:-<your-ip>})"
echo "  TLS: Caddy auto-provisions a Let's Encrypt cert on first HTTPS request."
echo ""
echo "  Room token secret: saved in .env (ROOMKIT_ROOM_TOKEN_SECRET)"
echo "  Do NOT share .env or commit it to version control."
echo "  Use the secret to sign HS256 JWTs — see .env for the token format."
echo ""
